title: "Storybook 7 + Vue 3 + TypeScript によるコンポーネントカタログのはじめかた"
summary: |-
  想定読者や使い方などについては「はじめに」の章をご覧ください。
topics: ["javascript", "vue", "vite", "storybook"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - summary
  - what_is_storybook
  - difference_from_v6
  - setup_project
  - create_sample_component
  - setup_storybook
  - create_main_js
  - first_story
  - story_and_csf
  - how_to_write_csf
