title: "Storybook 7 を Vue 3 + TypeScript ではじめよう！"
summary: |-
  想定読者や使い方などについては「はじめに」の章をご覧ください。
topics: ["javascript", "vue", "vite", "storybook"]
published: false
price: 500
chapters:
  - summary
  - what_is_storybook
  - difference_from_v6
  - setup_project
  - create_sample_component
  - setup_storybook
  - create_main_js
  - first_story
  - story_and_csf
  - how_to_write_csf
  - multiple_story
  - what_is_addon
  - addon_controls
  - addon_actions
  - addon_viewport
  - addon_background
  - addon_measure_outline
  - addon_docs
  - preview_js
  - decorators
  - play_function
  - test-runner
  - vue-i18n
  - pinia
  - vue-router
